# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(blank=True, upload_to='book_image'),
        ),
    ]
